configMapGenerator:
  - name: primary-file-vol
    files:
      - Dockerfile
      - package.json
      - package-lock.json
      - server.js
      - calc.js
      - test.js
generatorOptions:
  disableNameSuffixHash: true