apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EnforceLivenessProbe
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-100"
  name: enforcelivenessprobe
spec:
  match:
    kinds:
    - apiGroups:
      - ""
      - apps
      kinds:
      - Pod
      - ReplicaSet
      - ReplicationController
      - Deployment
      - StatefulSet
      - DaemonSet
