name: Testing

on:
  push:
    branches: main
  pull_requests:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo 
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: '17.*'
          registry-url: https://registry.npmjs.org
          scope: '@octocat'

      - name: Install dependencies
        run: npm install

      - name: NPM Test
        run: npm test 
